name: Test

on:
    push:
        branches: ["release", "develop"]
    pull_request:
        branches: ["release", "develop"]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm" # npm 쓰면 npm, yarn이면 yarn, pnpm이면 pnpm

            - name: Install dependencies
              run: |
                  npm ci || npm install

            - name: Run tests
              run: |
                  npm test -- --runInBand
